scheduler:
  interval_minutes: 1
  batch_size: 10

worker:
  concurrency: 2

crawler_db:
  host: 10.17.4.106
  port: 3306
  user: root
  password: '123456'
  database: ruoyi-vue-pro

result_db:
  host: 10.17.4.106
  port: 3306
  user: root
  password: '123456'
  database: ruoyi-vue-pro

redis:
  host: localhost
  port: 6379

faster_whisper:
  model_size: base
  device: cpu
